dataset:
  url: "hf://datasets/MounikaV/intel-cpu-dataset/intel dataset.csv"
features:
  primary_field:
    - vm_id
  required_fields:
    - vm_id
    - timestamp
    - task_status
  continuous:
    - cpu_usage
    - memory_usage
    - network_traffic
    - power_consumption
    - num_executed_instructions
    - execution_time
    - energy_efficiency
  nominal:
    - task_type
  ordinal:
    task_priority: ["low", "medium", "high"]
  target: "is_anomalous"
  columns_to_drop:
    - vm_id
    - timestamp
    - task_status
split:
  train: 0.7
  val: 0.15
  test: 0.15

