cloud_api:
  base_url: https://127.0.0.1:443
  endpoints:
    escalate_issue: /escalate_issue
    generate_advice: /generate_advice
    log_error: /log_error
    model_download: /load_local_model
    rules_download: /load_local_rules
  verify_cert: false
machine_api:
  base_url: http://127.0.0.2:8000
  endpoints:
    generate_advice: /generate_advice
    generate_system_parameters: /generate_system_parameters
privacy:
  choice_prompt: 'Enter your choice (1-3): '
  intro_message: '

    Enable Intelligent Support?

    ---------------------------


    To provide proactive, AI-driven system optimization and support, this assistant
    collects

    diagnostic data like CPU usage, system temperature, and application performance.

    You control what is shared.


    1. [ ] Share with Dell to receive full support and updates

    2. [ ] Keep data local to device only

    3. [ ] Do not collect telemetry at all

    '
  mode: unset
  mode_options:
  - unset
  - share_with_dell
  - local_only
  - disable_telemetry
  options:
    '1': share_with_dell
    '2': local_only
    '3': disable_telemetry
  stmt: '

    Note: The privacy mode is currently set to `{privacy_mode}`.

    To modify it, navigate to the file located at `{telemetry_config_path}`,

    find the `mode` field, and update its value to `unset`.

    '
storage:
  local_model_path: edge/random_forest_model.joblib
  local_rules_path: edge/edge_rules.json
telemetry:
  menu_option: '

    Select an item to test:

    0: Testing Normal Temperature

    1: Testing Moderate Temperature to reduce screen brightness

    2: Testing Moderate Temperature to increase fan speed

    3: Testing High Temperature to enable additional cooling

    4: Testing Critical Temperature to shutdown machine

    9: Exit'
