cloud_api:
  # base_url: https://127.0.0.1:443
  base_url: http://127.0.0.1:8000
  endpoints:
    escalate_issue: /escalate_issue
    model_download: /load_local_model
    rules_download: /load_local_rules
    generate_advice: /generate_advice
machine_api:
  base_url: http://127.0.0.2:8000
  endpoints:
    generate_advice: /generate_advice
    generate_system_parameters: /generate_system_parameters
storage:
  local_model_path: edge/received_model.joblib
  local_rules_path: edge/received_rules.json
telemetry:
  choice_prompt: 'Enter your choice (1-3): '
  intro_message: 'Enable Intelligent Support?

    To provide proactive, AI-driven system optimization and support, this assistant
    collects

    diagnostic data like CPU usage, system temperature, and application performance.

    You control what is shared.


    1. [ ] Share with Dell to receive full support and updates

    2. [ ] Keep data local to device only

    3. [ ] Do not collect telemetry at all

    '
  mode: unset
  mode_options:
  - unset
  - share_with_dell
  - local_only
  - disable_telemetry
  options:
    '1': share_with_dell
    '2': local_only
    '3': disable_telemetry
test_item: 3
