cloud_api:
  base_url: https://127.0.0.1:443
  endpoints:
    generate_advice: /generate_advice
    rules_download: /load_local_rules
    model_download: /load_local_model
machine_api:
  base_url: http://127.0.0.2:8000
  endpoints:
    generate_advice: /generate_advice
    generate_system_parameters: /generate_system_parameters
storage:
  local_model_path: edge/received_model.joblib
  local_rules_path: edge/received_rules.json  
telemetry:
  mode: share_with_dell
  mode_options:
  - unset
  - share_with_dell
  - local_only
  - disable_telemetry
test_item: 1
